# Generated by Django 5.2.15 on 2026-06-10 14:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('location_type', models.CharField(choices=[('bake_stand', 'Bake Stand'), ('food_truck', 'Food Truck'), ('popup', 'Pop-up'), ('farm_stand', 'Farm Stand')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('street_address', models.CharField(blank=True, max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('attendance', models.CharField(choices=[('attended', 'Attended'), ('unattended', 'Unattended (honor stand)')], default='attended', help_text='For unattended honor stands, hours mean "stocked," not staffed.', max_length=12)),
                ('irregular_hours_note', models.CharField(blank=True, help_text='Free text for patterns the weekly schedule cannot express. Not used by the open-now filter.', max_length=300)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('tiktok', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('delisted', 'Delisted')], default='draft', max_length=10)),
                ('validation_score', models.PositiveSmallIntegerField(default=100, help_text='Drops when users report problems. Low score triggers admin review — never automatic delisting.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='stands', to='stands.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_stands', to=settings.AUTH_USER_MODEL)),
                ('payment_methods', models.ManyToManyField(blank=True, related_name='stands', to='stands.paymentmethod')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('contact', models.CharField(blank=True, help_text='Optional email/phone.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled', models.BooleanField(default=False)),
                ('handled_note', models.CharField(blank=True, max_length=300)),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='stands.stand')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stands/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('approved', models.BooleanField(default=False, help_text='Manual approval before display.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='stands.stand')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClaimRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified in person'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='stands.stand')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_hours', to='stands.stand')),
            ],
            options={
                'verbose_name_plural': 'weekly hours',
                'ordering': ['weekday', 'open_time'],
            },
        ),
        migrations.CreateModel(
            name='DayOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('is_open', models.BooleanField(default=True)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_overrides', to='stands.stand')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('stand', 'date')},
            },
        ),
    ]
