# Generated by Django 5.2.15 on 2026-06-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Admin-only research notes; never shown publicly.'),
        ),
    ]
