# Generated by Django 5.2.15 on 2026-06-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0002_stand_internal_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='coords_source',
            field=models.CharField(blank=True, choices=[('owner_pin', 'Owner-placed pin'), ('admin', 'Admin-placed pin'), ('geocoded', 'Auto-geocoded from address')], help_text='Where the coordinates came from. Human-placed pins are never overwritten by the geocoder.', max_length=10),
        ),
        migrations.AddField(
            model_name='stand',
            name='geocode_precision',
            field=models.CharField(blank=True, help_text='Nominatim result type (house, street, hamlet...). Rural addresses often resolve to street level only.', max_length=30),
        ),
        migrations.AddField(
            model_name='stand',
            name='geocoded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
