# Generated by Django 5.2.15 on 2026-06-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0003_stand_coords_source_stand_geocode_precision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='claim_token',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stand',
            name='claimed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
