# Generated by Django 5.2 on 2026-06-12 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0004_stand_claim_token_stand_claimed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='moderation',
            field=models.CharField(choices=[('pending', 'Pending review'), ('auto', 'Auto-approved (moderation passed)'), ('flagged', 'Flagged by moderation'), ('manual', 'Manually reviewed')], default='pending', help_text='Automated moderation outcome. "approved" is the display gate; this records how it was decided.', max_length=10),
        ),
        migrations.AddField(
            model_name='photo',
            name='moderation_detail',
            field=models.CharField(blank=True, help_text='Scores/categories from the moderation backend.', max_length=200),
        ),
        migrations.AddField(
            model_name='stand',
            name='list_photo',
            field=models.ForeignKey(blank=True, help_text='The gallery photo the list thumbnail was made from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stands.photo'),
        ),
        migrations.AddField(
            model_name='stand',
            name='list_thumb',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='thumbs/'),
        ),
    ]
