# Generated by Django 5.2.15 on 2026-06-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0005_photo_moderated_at_photo_moderation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='auto_hidden',
            field=models.BooleanField(default=False, help_text='Reserved for the (deferred) report auto-hide: withholds a stand from public view pending review. v1.1 uses manual review, so this stays False for now.'),
        ),
        migrations.AddField(
            model_name='stand',
            name='created_via',
            field=models.CharField(choices=[('admin_seed', 'Admin / seed / import'), ('public_submit', 'Public submission')], default='admin_seed', help_text='How this listing entered the system.', max_length=15),
        ),
        migrations.AddField(
            model_name='stand',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='When a public submission arrived (blank for admin/seed).', null=True),
        ),
        migrations.AddField(
            model_name='stand',
            name='verification',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified')], default='unverified', help_text='Verified stands appear in the default public view; unverified (community-submitted) stands are hidden behind a toggle.', max_length=10),
        ),
        migrations.AddField(
            model_name='stand',
            name='verified_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='stand',
            name='verified_via',
            field=models.CharField(blank=True, choices=[('admin', 'Admin approval'), ('claim', 'Owner claim')], max_length=10),
        ),
    ]
