# Generated by Django 5.2.15 on 2026-06-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0008_facebook_full_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='threads',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
