"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import base64
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- environment configuration ---------------------------------------------
# WHERE SETTINGS COME FROM:
#   * Production: systemd injects all config into the gunicorn process via an
#     EnvironmentFile (the prod .env at the app root). systemd is the source of
#     truth in prod; the .p8 / multi-line secrets are base64-encoded so they
#     survive EnvironmentFile parsing. Nothing below overrides those values.
#   * Local dev: there is no systemd, so we optionally read a local .env here.
#     Use os.environ.setdefault() so anything already in the real environment
#     (i.e. systemd in prod) always wins and is never clobbered by this file.
# To verify the *live* value, read the running process, not a manual shell
# (a manual `manage.py` run has none of the systemd vars):
#     sudo cat /proc/$(pgrep -f gunicorn | head -1)/environ | tr '\0' '\n' | grep -i debug
_env_file = BASE_DIR / '.env'
if _env_file.exists():
    for _line in _env_file.read_text().splitlines():
        _line = _line.strip()
        if not _line or _line.startswith('#') or '=' not in _line:
            continue
        _k, _, _v = _line.partition('=')
        os.environ.setdefault(_k.strip(), _v.strip().strip('"').strip("'"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY ALWAYS comes from the environment in production (systemd injects it
# from /opt/hilobakestands/.env). The literal below is a DEV-ONLY throwaway and
# is NEVER used in prod — it only applies when no SECRET_KEY env var is set
# (i.e. local dev). Its `django-insecure-` prefix is Django's own marker for a
# non-production key, so `manage.py check --deploy` flags it if it ever leaks
# into a real deploy. To rotate prod: change SECRET_KEY in the box's .env and
# restart (invalidates existing sessions, which is expected on a key rotation).
SECRET_KEY = os.environ.get('SECRET_KEY') or 'django-insecure-+0ay1xvfd-l4l(xg+9+)(z_g^5*r5z42)dwkudnv8f2+ps3@lv'

# SECURITY WARNING: don't run with debug turned on in production!
# Fail-CLOSED: defaults to OFF. Debug only turns on when something explicitly
# sets DEBUG=1 (your local .env). A missing/typo'd config can never silently
# expose tracebacks or the .env in production. Prod systemd sets DEBUG=0.
DEBUG = os.environ.get('DEBUG', '0') == '1'

# Fail-LOUD: in production (DEBUG off) a real SECRET_KEY must come from the
# environment. Without this guard, a missing env var would silently fall back to
# the public dev literal above — so we refuse to boot instead. (Checked here,
# after DEBUG is known; dev is unaffected because DEBUG is on locally.)
if not DEBUG and not os.environ.get('SECRET_KEY'):
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        'SECRET_KEY must be set in the environment when DEBUG is off. '
        'Set it in /opt/hilobakestands/.env (prod) and restart.'
    )

ALLOWED_HOSTS = [h for h in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h]
CSRF_TRUSTED_ORIGINS = [o for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o]


# Application definition

INSTALLED_APPS = [
    'django.contrib.sites',
    'stands',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.apple',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'stands.middleware.UsageLogMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get('DB_PATH', BASE_DIR / 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'Pacific/Honolulu'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- HiloBakeStands additions ---
import os

LANGUAGES = [('en', 'English'), ('ja', 'Japanese')]
LOCALE_PATHS = [BASE_DIR / 'locale']

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]
SITE_ID = 1
# Canonical public origin; used to build absolute URLs (e.g. claim links)
SITE_BASE_URL = os.environ.get('SITE_BASE_URL', 'https://hilobakestands.com')
LOGIN_REDIRECT_URL = '/'
ACCOUNT_EMAIL_VERIFICATION = 'none'  # identity comes from Google/Apple
# allauth's post-login flash ("Successfully signed in as …") and the
# {% user_display %} tag default to the auto-generated, lowercased username.
# Show the proper-cased name from the OAuth profile instead, so the flash
# matches the "Aloha, {first_name}" header greeting.
ACCOUNT_USER_DISPLAY = lambda user: (
    user.first_name or user.get_full_name() or user.email or user.username)
# Trust provider-verified emails: same email via Google or Apple = same user
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        # email is the cross-provider identity key (matches Apple sign-in later)
        'SCOPE': ['profile', 'email'],
        'APP': {
            'client_id': os.environ.get('GOOGLE_CLIENT_ID', ''),
            'secret': os.environ.get('GOOGLE_CLIENT_SECRET', ''),
        },
    },
    'apple': {'APP': {
        # Services ID (web flow client), e.g. com.hilobakestands.signin
        'client_id': os.environ.get('APPLE_CLIENT_ID', ''),
        # 10-char Key ID of the Sign in with Apple private key
        'secret': os.environ.get('APPLE_KEY_ID', ''),
        # 10-char Team ID (App ID prefix)
        'key': os.environ.get('APPLE_TEAM_ID', ''),
        # .p8 contents, base64-encoded to survive systemd EnvironmentFile
        # (which can't hold multi-line values)
        'settings': {'certificate_key': base64.b64decode(
            os.environ.get('APPLE_PRIVATE_KEY_B64', '')).decode() or None},
    }},
}

MEDIA_URL = '/media/'
# Prod sets MEDIA_ROOT=/opt/hilobakestands/media (outside the app dir):
# deploys mirror the app dir with --delete, and the systemd unit only
# grants write access to /opt/hilobakestands/media. Local dev default
# stays inside the repo (gitignored).
MEDIA_ROOT = Path(os.environ.get('MEDIA_ROOT', BASE_DIR / 'media'))
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Email via Google Workspace legacy account (SPEC 5a)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')  # app-specific password
# Friendly From display name lives HERE in code, not the .env: the value has
# spaces + angle brackets that systemd's EnvironmentFile would mangle (keeps
# quotes literal). The address stays matt@hilobakestands.com — the verified
# Gmail "send mail as" alias — so SPF/DKIM/DMARC alignment is unaffected; only
# the display name changes (clients previously showed bare "matt").
# `or` (not a .get default) so an empty DEFAULT_FROM_EMAIL= in prod .env still
# falls through to this friendly default instead of an empty From.
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL') or 'Hilo Bake Stands <matt@hilobakestands.com>'
SERVER_EMAIL = DEFAULT_FROM_EMAIL  # From: address for mail_admins
ADMINS = [('Matthew', os.environ.get('ADMIN_EMAIL', 'matt@giampapa.com'))]

# Cloudflare Turnstile (bot protection on public forms). If the secret is
# unset (dev, tests), verification is skipped entirely.
TURNSTILE_SITE_KEY = os.environ.get('TURNSTILE_SITE_KEY', '')
TURNSTILE_SECRET_KEY = os.environ.get('TURNSTILE_SECRET_KEY', '')

# Photo moderation. Primary: Google Vision SafeSearch (free 1000/month).
# Fallback: NSFW service on media.home. Both optional — unset backends are
# skipped, and unmoderated photos simply stay pending for manual review.
VISION_API_KEY = os.environ.get('VISION_API_KEY', '')
MODERATION_FALLBACK_URL = os.environ.get('MODERATION_FALLBACK_URL', '')
MODERATION_FALLBACK_TOKEN = os.environ.get('MODERATION_FALLBACK_TOKEN', '')

# Privacy-preserving usage log (stands.middleware.UsageLogMiddleware).
# Append-only JSONL; no cookies/JS/3rd-party. Unset = DISABLED (opt-in).
# On prod set USAGE_LOG_PATH=/opt/hilobakestands/data/usage.jsonl in .env.
USAGE_LOG_PATH = os.environ.get('USAGE_LOG_PATH') or None

# --- production hardening (no-ops in DEBUG) ---
if not DEBUG:
    STORAGES = {
        'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
        'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
    }
    # Behind Cloudflare Tunnel: cloudflared talks plain HTTP to gunicorn on localhost.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Stated explicitly for audit clarity (Django already defaults this to True):
    # the session cookie is never readable by JavaScript, limiting XSS theft.
    SESSION_COOKIE_HTTPONLY = True
    # Safe here because CSRF tokens are delivered via Django's hidden form field
    # ({% csrf_token %}), NOT read from the cookie by JS. Verified: no fetch()/
    # XHR POSTs and nothing reads document.cookie anywhere in templates/static.
    # If client-side JS is ever added that needs the token from the cookie, this
    # must go back to False (Django's default) or that JS will fail CSRF checks.
    CSRF_COOKIE_HTTPONLY = True

    # HSTS and HTTP->HTTPS enforcement are handled at the CLOUDFLARE EDGE, not here:
    #   * "Always Use HTTPS" redirects http->https before traffic reaches origin.
    #   * HSTS (Strict-Transport-Security) is configured in Cloudflare SSL/TLS ->
    #     Edge Certificates -> HSTS, where it's easy to ramp/roll back. Preload is
    #     a one-way commitment, so it's managed deliberately at the edge.
    # If HSTS is ever moved into Django, set SECURE_HSTS_SECONDS /
    # SECURE_HSTS_INCLUDE_SUBDOMAINS / SECURE_HSTS_PRELOAD here and turn off the
    # Cloudflare setting to avoid duplicate/conflicting headers.
